//
//  GuessSongAry.swift
//  guessTheSong
//
//  Created by 林伯翰 on 2019/12/9.
//  Copyright © 2019 Bruce Lin. All rights reserved.
//

import Foundation

struct GuessSong {
    var SongName: String
    var SongAnswer: String
    var SongHints: String
}

let songDataBase = ["The Ocean",
                    "Alone Alan Walker",
                    "All Falls Down Alan Walker",
                    "Closer",
                    "Faded",
                    "The Day you went away",
                    "Something Just Like This",
                    "She Is My Sin",
                    "Nevada",
                    "Tired Alan Walker",
                    "Perfect Strangers",
                    "There For You",
                    "The Nights",
                    "Live while We're Young",
                    "How Long Will I Love You",
                    "Shape Of You",
                    "頑童 幹大事",
                    "頑童 South Side",
                    "金莎 夢千年之戀",
                    "金莎 星月神話",
                    "玖壹壹 打鐵",
                    "玖壹壹 凍未條",
                    "玖壹壹 9453",
                    "玖壹壹 嘻哈庄腳情",
                    "愛這件事情",
                    "理想情人",
                    "我當你空氣",
                    "F.I.R 星火",
                    "黃義達 那女孩對我說",
                    "追光者",
                    "Karra Make Me Move",
                    "Waiting For Love Avicii",
                    "Wake Me Up Avicii",
                    "范瑋琪",
                    "踮起腳尖愛",
                    "魔鬼中的天使",
                    "怎麼還不愛",
                    "浪漫來襲",
                    "小さな恋のうた",
                    "Lost Stars",
                    "A Thousand Miles",
                    "Christina Perri A Thousand Years",
                    "Lady Gaga The Cure",
                    "Love Me Like You Do",
                    "Despacito",
                    "Paris",
                    "G-Eazy Good Life",
                    "Timber",
                    "Rain Over Me",
                    "Stop Crying Your Heart Out",
                    "Jonas Blue Mama",
                    "黎明 看上她",
                    "Lucenzo Danza Kuduro",
                    "The Chainsmokers Young",
                    "Zedd Stay",
                    "Falling Slowly",
                    "When you Believe",
                    "Counting Stars",
                    "Alan Walker The Spectre",
                    "We Don't Talk Anymore",
                    "Clean Bandit Symphony",
                    "Rockabye",
                    "See You Again",
                    "Amazing Facsimile",
                    "Sing Me To Sleep",
                    "Lisa Still Alive",
                    "Rhythm Of Love",
                    "Dont trust me",
                    "鄧紫棋 光年之外",
                    "任賢齊 永不退縮",
                    "勢在必行",
                    "前前前世",
                    "Radwimps Zenzenzense",
                    "Radwimps Dream Lantern",
                    "Radwimps Sparkle",
                    "Radwimps Nandemonaiya",
                    "一個像夏天一個像秋天",
                    "信樂團 One Night In 北京",
                    "口袋的天空",
                    "梁靜茹 屬於",
                    "梁靜茹 暖暖",
                    "五天幾年",
                    "你是我的OK蹦",
                    "胡夏 那些年",
                    "白安 兜風",
                    "白安 不聽",
                    "白安 放空",
                    "白安 是什麼讓我遇見這樣的你",
                    "白安 默劇",
                    "白安 Bird",
                    "麥田捕手",
                    "白安 讓我逃離平庸的生活",
                    "白安 我只想在乎我在乎的",
                    "白安 若你真的有想過",
                    "Lorde Everybody Wants to rule the world",
                    "Lily Allen Little Soldier",
                    "Leona I See You",
                    "Too Good At Goodbyes",
                    "Use Somebody",
                    "Wolves",
                    "Numb",
                    "Need You Now",
                    "More Than You Know",
                    "Me Too",
                    "Love Yourself",
                    "Lovers Carvings",
                    "I Took A Pill In Ibiza",
                    "The Hanging Tree",
                    "Glad You Came",
                    "Libera God Rest You Merry Gentlemen",
                    "The Dream Within",
                    "Nelly Dilemma",
                    "Kylie Dacing",
                    "Charlie Attention",
                    "All Star",
                    "2U",
                    "7 Minutes"
                    
]
